core_generate_barcode:
  path: /barcode/generate/{value}.{extension}
  defaults:
      _controller: CoreBundle:Barcode:generate
      barcodeType: C128

  requirements:
    extension: svg|jpg|png



# This route should be the last one defined
remove_trailing_slash:
    path: /{url}
    defaults:
        _controller: CoreBundle:Redirect:removeTrailingSlash

    requirements:
        url: .*/$
    methods: [GET]
