services:
    core.service.random_string_service:
        class: CoreBundle\Service\RandomStringService
        calls:
            - [generateRandomString, ['@?']]

    gedmo.listener.blameable:
            class: Gedmo\Blameable\BlameableListener
            tags:
                - { name: doctrine.event_subscriber, connection: default }
            calls:
                - [ setAnnotationReader, [ "@annotation_reader" ] ]
