student_management_list:
    path:     /list
    defaults:
      _controller: UserBundle:Student:list
    requirements:
      page: \d+

student_management_new:
    path: /new
    defaults:
      _controller: UserBundle:Student:new

student_management_import:
    path: /import
    defaults:
      _controller: UserBundle:Student:import

student_management_results:
    path: /result
    defaults:
      _controller: UserBundle:Student:results
    options:
        expose: true

student_management_details:
    path: /details/{id}
    defaults:
      _controller: UserBundle:Student:details
    options:
      expose: true

student_management_edit:
    path: /edit/{id}
    defaults:
      _controller: UserBundle:Student:edit
    options:
        expose: true
