user_management_list:
    path:     /list
    defaults:
      _controller: UserBundle:User:list
    requirements:
      page: \d+

user_management_new:
    path: /new
    defaults:
      _controller: UserBundle:User:new

user_management_results:
    path: /result
    defaults:
      _controller: UserBundle:User:results
    options:
        expose: true

user_management_details:
    path: /details/{id}
    defaults:
      _controller: UserBundle:User:details
    options:
      expose: true

user_management_edit:
    path: /edit/{id}
    defaults:
      _controller: UserBundle:User:edit
    options:
        expose: true
