checks:
    php: true

filter:
    excluded_paths:
        - 'tests/*'
        - 'var/*'
        - 'bin/*'
        - 'app/AppCache.php'
        - 'app/AppKernel.php'
        - 'web/config.php'
        - 'web/app.php'
        - '**/bundle.*.js'
        - '**/shared.*.js'
        - '**/bundle.js'
        - '**/shared.js'
