version: '2'

services:
  app:
    image: debian:jessie
    volumes:
      - .:/var/www/${COMPOSE_PROJECT_NAME}

  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devtools/nginx-vhost.d:/etc/nginx/vhost.d:ro
    networks:
      - frontend
      - adsdaq_proxy-tier

  php:
    image: he8us/php-fpm-prod:7.0
    expose:
      - "9000"
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
      TIMEZONE: "Europe/Brussels"
    volumes_from:
      - app
    networks:
      - backend

  php-cli:
    image: he8us/php-cli:7.0
    environment:
      APPLICATION_ENV: ${APPLICATION_ENV}
    volumes:
      - ~/.ssh:/root/.ssh:ro
      - composer-cache:/root/.composer
    volumes_from:
      - app
    working_dir: /var/www/${COMPOSE_PROJECT_NAME}
    networks:
      - backend

  nginx:
    image: he8us/nginx-symfony
    expose:
      - "80"
    environment:
      VIRTUAL_HOST: www.${MASTER_DOMAIN}
      DOCUMENT_ROOT: /var/www/${COMPOSE_PROJECT_NAME}/web
      APPLICATION_ENV: ${APPLICATION_ENV}
      LOG_FILE: ${COMPOSE_PROJECT_NAME}
    volumes_from:
      - app
    depends_on:
      - php
    networks:
      - frontend
      - backend

  mysql:
    image: mysql:5.6
    ports:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - backend

volumes:
  mysql-data:
  composer-cache:

networks:
  adsdaq_proxy-tier:
    external: true
  backend:
  frontend:
