student_calendar:
    prefix: /calendar
    resource: "@StudentBundle/Resources/config/routing/calendar.yml"


student_dashboard:
  prefix: /dashboard
  resource: "@StudentBundle/Resources/config/routing/dashboard.yml"

teacher_lesson:
  prefix: /lesson
  resource: "@StudentBundle/Resources/config/routing/lesson.yml"
