course_homepage:
    path:     /
    defaults: { _controller: CourseBundle:Default:index }

course_course_content:
    resource: "@CourseBundle/Resources/config/routing/coursecontent.yml"
    prefix:   /content

