services:
    courses.datatable.content:
        class: CourseBundle\Datatables\CourseContentDatatable
        parent: sg_datatables.datatable.abstract

    courses.datatable.grade:
        class: CourseBundle\Datatables\GradeDatatable
        parent: sg_datatables.datatable.abstract

    courses.datatable.grade_class:
        class: CourseBundle\Datatables\GradeClassDatatable
        parent: sg_datatables.datatable.abstract

    courses.datatable.lesson:
        class: CourseBundle\Datatables\LessonDatatable
        parent: sg_datatables.datatable.abstract

    course.services.gradeclass:
        class: CourseBundle\Service\GradeClassService
        arguments: ['@doctrine']

    course.services.coursecontent:
        class: CourseBundle\Service\CourseContentService
        arguments: ['@doctrine']

    course.services.grade:
        class: CourseBundle\Service\GradeService
        arguments: ['@doctrine']

    course.services.lesson:
        class: CourseBundle\Service\LessonService
        arguments: ['@doctrine']
