services:
    cms.twig_extension:
        class: CMSBundle\Twig\CMSExtension
        public: false
        tags:
          - { name: twig.extension }

    cms.menu_chain:
        class: CMSBundle\Menu\MenuChain

    cms.menu.pages:
        class: CMSBundle\Menu\MenuItem
        arguments:
        tags:
          - {name: cms.menu.item, position: left_menu}


#    cms.example:
#        class: CMSBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
