user_security:
  prefix: /
  resource: "@UserBundle/Resources/config/routing/security.yml"

user_profile:
  prefix: /profile
  resource: "@UserBundle/Resources/config/routing/profile.yml"

user_management:
  prefix: /manage
  resource: "@UserBundle/Resources/config/routing/management.yml"
