course_content_index:
    path:     /
    defaults: { _controller: "CourseBundle:CourseContent:index" }
    methods:  GET

course_content_show:
    path:     /{id}/show
    defaults: { _controller: "CourseBundle:CourseContent:show" }
    methods:  GET

course_content_new:
    path:     /new
    defaults: { _controller: "CourseBundle:CourseContent:new" }
    methods:  [GET, POST]

course_content_edit:
    path:     /{id}/edit
    defaults: { _controller: "CourseBundle:CourseContent:edit" }
    methods:  [GET, POST]

course_content_delete:
    path:     /{id}/delete
    defaults: { _controller: "CourseBundle:CourseContent:delete" }
    methods:  DELETE

course_content_results:
    path:     /result
    defaults: { _controller: "CourseBundle:CourseContent:results" }
    methods:  GET
