cms_page_index:
    path:     /
    defaults: { _controller: "CmsBundle:Page:index" }
    methods:  GET

cms_page_show:
    path:     /{id}/show
    defaults: { _controller: "CmsBundle:Page:show" }
    methods:  GET
    options:
         expose: true

cms_page_new:
    path:     /new
    defaults: { _controller: "CmsBundle:Page:new" }
    methods:  [GET, POST]

cms_page_edit:
    path:     /{id}/edit
    defaults: { _controller: "CmsBundle:Page:edit" }
    methods:  [GET, POST]
    options:
            expose: true

cms_page_delete:
    path:     /{id}/delete
    defaults: { _controller: "CmsBundle:Page:delete" }
    methods:  DELETE

cms_page_results:
    path: /result
    defaults: { _controller: "CmsBundle:Page:results" }
